version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - doxygen ./extras/docs/Doxyfile

sphinx:
  builder: html
  configuration: ./extras/docs/conf.py

python:
  install:
    - requirements: ./extras/docs/requirements.txt
